version: 2
updates:
  # Maintain dependencies for our yarn packages.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies:"

  # Maintain dependencies for our github actions dependencies.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies:"


